/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_pison_able_BluetoothCentralNative */

#ifndef _Included_com_pison_able_BluetoothCentralNative
#define _Included_com_pison_able_BluetoothCentralNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    setup
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_setup
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    scanForDevices
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;I)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_scanForDevices
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    populateServices
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;Lcom/pison/able/BluetoothDevice;)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_populateServices
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    readFromCharacteristic
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;Lcom/pison/able/BluetoothDevice;Ljava/util/UUID;Ljava/util/UUID;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_pison_able_BluetoothCentralNative_readFromCharacteristic
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    subscribeToNotifications
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;Lcom/pison/able/BluetoothDevice;Ljava/util/UUID;Ljava/util/UUID;)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_subscribeToNotifications
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    writeToCharacteristic
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;Lcom/pison/able/BluetoothDevice;Ljava/util/UUID;Ljava/util/UUID;[B)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_writeToCharacteristic
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jbyteArray);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    unsubscribeToNotifications
 * Signature: (Lcom/pison/able/BluetoothStatusChangeReceiver;)V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_unsubscribeToNotifications
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pison_able_BluetoothCentralNative
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pison_able_BluetoothCentralNative_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
